app:
  auth:
    sign-up-url: /auth/sign-up
    login-url: /auth/login
  jwt:
    key: 'ThisIsMyKey'
    expiration: 864_000_000 # 10 days
    token-prefix: 'Bearer '
    header: 'Authorization'


spring:
  application:
    name: spring-hello
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
server:
  port: 8080
---
spring:
  profiles: prod
server:
  port: ${PORT}